name: Build Mobile APK
on: [push, workflow_dispatch]

# Убираем плашку предупреждения на серверах GitHub
env:
  FORCE_JUST_ACTIONS_TO_NODE24: 'true'
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set Java Home Environment
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install --upgrade buildozer cython==0.29.36 setuptools virtualenv

      - name: Auto Configuration Spec File
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/#\? \?requirements =.*/requirements = python3,kivy/g' buildozer.spec
          sed -i 's/#\? \?android.api =.*/android.api = 33/g' buildozer.spec
          sed -i 's/#\? \?android.minapi =.*/android.minapi = 24/g' buildozer.spec
          sed -i 's/#\? \?android.ndk =.*/android.ndk = 25b/g' buildozer.spec
          sed -i 's/#\? \?p4a.branch =.*/p4a.branch = master/g' buildozer.spec

      - name: Build APK with Buildozer
        run: |
          yes y | buildozer -v android debug

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tracker-Mobile-APK
          path: bin/*.apk
